server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/crazycoder119/Asignment-2-cloud-config-store
          search-paths:
            - 'service-config/*service'
          #username: root
          #passphrase: 12345